GRANT CONNECT ON DATABASE suumo TO akim;
GRANT USAGE ON SCHEMA user_info TO akim;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA user_info TO akim;
GRANT ALL PRIVILEGES ON DATABASE suumo TO akim;
ALTER USER akim CREATEDB;

